spring:
  application:
    name: user_service

  datasource:
    url: jdbc:postgresql://localhost:5433/pes
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ejb:
          interceptor: org.hibernate.envers.event.EnversIntegrator
        envers:
          audit_table_suffix: _history
          store_data_at_delete: true
          global_with_modified_flag: true

server:
  servlet:
    context-path: /user-service

logging:
  level:
    root: INFO

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

secret: 7CA6AFDA-B94C-4CCF-AC45-7C802BR5745F